---

  - name: Create new route table for public subnet
    ec2_vpc_route_table:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      state: present
      vpc_id: "{{ ansibleVPC.vpc.id }}"
      tags:
        Name: rt_ansibleVPC_PublicSubnet
      subnets: 
        - "{{ public_subnet.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
      gateway_id: "{{ ansibleVPC_igw.gateway_id }}"
    register: rt_ansibleVPC_PublicSubnet

  - name: Display public route table
    debug:
      var: rt_ansibleVPC_PublicSubnet