---

  - name: Create Internet gateway for ansibleVPC
    ec2_vpc_igw:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      state: present
      vpc_id: "{{ ansibleVPC.vpc.id }}"
      tags:
        Name: ansibleVPC_IGW
      register: ansibleVPC_igw

  - name: Display ansibleVPC IGW details
    debug:
      var: ansibleVPC_igw