---
# handlers file for users

  # - name: Reboot system
  #   reboot:

  - name: Restart apache2
    service: 
      name: apache2
      state: restarted
    when: ansible_facts['os_family'] == "Debian"

  - name: Restart Httpd
    service: 
      name: httpd
      state: restarted
    when: ansible_facts['os_family'] == "RedHat"
